FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm install --save-dev @nestjs/cli

COPY init.dev.sh .
RUN chmod +x init.dev.sh

EXPOSE 3000

CMD ["sh", "init.dev.sh"]