name: Auth service workflows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - 'services/Auth/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: | 
        cd services/Auth
        dotnet build Auth.sln
    - name: Test
      run: |
        cd services/Auth
        dotnet test Auth.sln --no-build --verbosity normal